server:
  port: 8091
spring:
  application:
    name: springboot-dubbo-provider
dubbo:
  application:
    name: springboot-dubbo-provider
  protocol:
    name: dubbo
    port: 18091
    host: 192.168.70.32
  registry:
    address: nacos://172.168.201.95:8848
    parameters:
      namespace: 69e108eb-936c-4c5b-9124-e1cebd7e58a3
    use-as-config-center: true
    use-as-metadata-center: true