server:
  port: 8084
spring:
  redis:
   # host: 127.0.0.1 # Redis服务器地址
   # port: 6379 # Redis端口
   # database: 0 # Redis 数据库索引（默认为 0）
    password: 12345678
    connect-timeout: 60000 # 连接超时时间（毫秒）
    cluster:
      nodes: # Redis 服务器地址
        - 127.0.0.1:6371
        - 127.0.0.1:6372
        - 127.0.0.1:6373
        - 127.0.0.1:6374
        - 127.0.0.1:6375
        - 127.0.0.1:6376
      max-redirects: 3
    lettuce:
      pool:
        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）默认值为-1
        max-wait: -1 # 最大阻塞等待时间(负数表示没限制) 默认值为-1
        max-idle: 100 # 连接池中的最大空闲连接 默认值为8
        min-idle: 0 # 连接池中的最小空闲连接 默认值为0