server:
  port: 8087

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://127.0.0.1:9100
  accessKey: test
  secretKey: 12345678
  defaultBucketName: default
  bucketName: minio-test